# Project 00: NumPy and Pandas

Практика базовых операций с `pandas` на датасете `credit_data.xlsx`.

In [57]:
import numpy as np
import pandas as pd

In [58]:
data = pd.read_excel('data/credit_data.xlsx')

In [59]:
data.shape

(10476, 17)

In [60]:
data.head()

,client_id,department,age,education,social_status,number_of_children,property,number_of_properties,value_of_properties,outcome,outcome_amount,time_worked_since_last_employment_mnth,curr_working_status,recent_salary,number_of_cars,car_value,SCORE
0,1,SP,19,Senior student,Single,0,No,0,0,No,0,8,Yes,1800,0,0,12.000000
1,2,MG,23,Сomplete higher education,Single,1,No,0,0,No,0,9,No,4800,1,50000,18.000000
2,3,SC,25,Secondary education,Married,0,Yes,1,220000,No,0,18,Yes,2200,2,30000,23.000000
3,4,PR,27,Senior student,Married,1,Yes,0,0,No,0,22,No,3900,0,0,28.666667
4,5,RJ,28,Сomplete higher education,Divorced,2,No,1,370000,No,0,30,Yes,NaN,1,35000,34.166667

In [61]:
data.tail()

,client_id,department,age,education,social_status,number_of_children,property,number_of_properties,value_of_properties,outcome,outcome_amount,time_worked_since_last_employment_mnth,curr_working_status,recent_salary,number_of_cars,car_value,SCORE
10471,10472,PR,51,Сomplete higher education,Single,1,No,0,0,No,0,9,No,4800,1,50000,18.000000
10472,10473,SP,48,Secondary education,Married,0,Yes,1,220000,No,0,18,Yes,2200,2,30000,23.000000
10473,10474,RJ,51,Senior student,Married,1,Yes,0,0,No,0,22,No,3900,0,0,28.666667
10474,10475,RJ,48,Сomplete higher education,Divorced,2,No,1,370000,No,0,30,Yes,NaN,1,35000,34.166667
10475,10476,PR,51,Secondary education,Divorced,0,No,0,0,No,0,14,Yes,3100,2,40000,39.666667

In [62]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10476 entries, 0 to 10475
Data columns (total 17 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   client_id                               10476 non-null  int64
 1   department                              10476 non-null  object
 2   age                                     10476 non-null  int64
 3   education                               10476 non-null  object
 4   social_status                           10476 non-null  object
 5   number_of_children                      10476 non-null  int64
 6   property                                10476 non-null  object
 7   number_of_properties                    10476 non-null  int64
 8   value_of_properties                     10476 non-null  int64
 9   outcome                                 10476 non-null  object
 10  outcome_amount                          10476 non-null  int64
 11  time_worked_since_last_employment_mnth  10476 non-null  int64
 12  curr_working_status                     10476 non-null  object
 13  recent_salary                           10474 non-null  object
 14  number_of_cars                          10476 non-null  int64
 15  car_value                               10476 non-null  int64
 16  SCORE                                   10476 non-null  float64
dtypes: float64(1), int64(9), object(7)
memory usage: 1.4+ MB

In [63]:
data.drop('client_id', axis=1, inplace=True)

In [64]:
data.groupby('recent_salary', dropna=True)['recent_salary'].count()

recent_salary
1800       846
2200       792
3100       792
3900       792
4500       468
4800       792
5300       522
6100       522
6800       611
9000       522
9800       468
11500      790
13000      522
15000      522
17500      522
18300      522
22000      468
no data      1
Name: recent_salary, dtype: int64

In [65]:
data[data['recent_salary'] == 'no data']

,department,age,education,social_status,number_of_children,property,number_of_properties,value_of_properties,outcome,outcome_amount,time_worked_since_last_employment_mnth,curr_working_status,recent_salary,number_of_cars,car_value,SCORE
10459,RJ,45,Senior student,Single,1,Yes,1,185000,Yes,3000,19,Yes,no data,0,0,45.166667

In [66]:
data.isna().sum(axis=0)

department                                0
age                                       0
education                                 0
social_status                             0
number_of_children                        0
property                                  0
number_of_properties                      0
value_of_properties                       0
outcome                                   0
outcome_amount                            0
time_worked_since_last_employment_mnth    0
curr_working_status                       0
recent_salary                             2
number_of_cars                            0
car_value                                 0
SCORE                                     0
dtype: int64

In [67]:
data[data['number_of_children'] > 0]

,department,age,education,social_status,number_of_children,property,number_of_properties,value_of_properties,outcome,outcome_amount,time_worked_since_last_employment_mnth,curr_working_status,recent_salary,number_of_cars,car_value,SCORE
1,MG,23,Сomplete higher education,Single,1,No,0,0,No,0,9,No,4800,1,50000,18.000000
3,PR,27,Senior student,Married,1,Yes,0,0,No,0,22,No,3900,0,0,28.666667
4,RJ,28,Сomplete higher education,Divorced,2,No,1,370000,No,0,30,Yes,NaN,1,35000,34.166667
6,MG,32,Senior student,Single,1,Yes,1,185000,Yes,3000,19,Yes,6800,0,0,45.166667
7,SC,35,Сomplete higher education,Single,1,Yes,2,450000,Yes,2400,25,Yes,22000,1,150000,50.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10468,SP,48,Senior student,Married,3,Yes,1,450000,Yes,3200,93,No,5300,0,0,94.666667
10469,RJ,51,Сomplete higher education,Widowed,1,No,3,900000,No,0,150,No,18300,1,80000,98.000000
10471,PR,51,Сomplete higher education,Single,1,No,0,0,No,0,9,No,4800,1,50000,18.000000
10473,RJ,51,Senior student,Married,1,Yes,0,0,No,0,22,No,3900,0,0,28.666667
10474,RJ,48,Сomplete higher education,Divorced,2,No,1,370000,No,0,30,Yes,NaN,1,35000,34.166667

In [68]:
data.groupby('social_status', dropna=True)['age'].mean()

social_status
Divorced    41.715278
Married     42.856870
Single      35.083333
Widowed     50.187500
Name: age, dtype: float64

In [69]:
data.groupby('department', dropna=True)['department'].count()

department
MG    1620
PR    1890
RJ    2916
SC    1620
SP    2430
Name: department, dtype: int64

In [70]:
data.sort_values(by='SCORE', ascending=True).head(10)

,department,age,education,social_status,number_of_children,property,number_of_properties,value_of_properties,outcome,outcome_amount,time_worked_since_last_employment_mnth,curr_working_status,recent_salary,number_of_cars,car_value,SCORE
0,SP,19,Senior student,Single,0,No,0,0,No,0,8,Yes,1800,0,0,12.0
1089,PR,32,Senior student,Single,0,No,0,0,No,0,8,Yes,1800,0,0,12.0
9025,SP,42,Сomplete higher education,Divorced,2,No,0,0,No,0,8,Yes,1800,0,0,12.0
6172,MG,30,Senior student,Single,0,No,0,0,No,0,8,Yes,1800,0,0,12.0
6171,SP,28,Secondary education,Divorced,1,No,0,0,No,0,8,Yes,1800,0,0,12.0
3205,SP,42,Сomplete higher education,Divorced,2,No,0,0,No,0,8,Yes,1800,0,0,12.0
9032,SC,62,Secondary education,Divorced,1,No,0,0,No,0,8,Yes,1800,0,0,12.0
3197,RJ,19,Secondary education,Divorced,1,No,0,0,No,0,8,Yes,1800,0,0,12.0
3212,SC,62,Secondary education,Divorced,1,No,0,0,No,0,8,Yes,1800,0,0,12.0
9049,SC,62,Secondary education,Divorced,1,No,0,0,No,0,8,Yes,1800,0,0,12.0

In [71]:
data[(data['property'] == 'Yes') & (data['number_of_cars'] > 0)]

,department,age,education,social_status,number_of_children,property,number_of_properties,value_of_properties,outcome,outcome_amount,time_worked_since_last_employment_mnth,curr_working_status,recent_salary,number_of_cars,car_value,SCORE
2,SC,25,Secondary education,Married,0,Yes,1,220000,No,0,18,Yes,2200,2,30000,23.000000
7,SC,35,Сomplete higher education,Single,1,Yes,2,450000,Yes,2400,25,Yes,22000,1,150000,50.666667
10,SP,48,Сomplete higher education,Divorced,2,Yes,2,600000,No,0,15,Yes,15000,1,70000,67.166667
11,MG,51,Secondary education,Divorced,1,Yes,0,0,No,0,80,No,6100,2,48000,72.666667
14,RJ,57,Secondary education,Married,3,Yes,1,340000,Yes,4000,90,Yes,13000,2,180000,89.166667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10460,SP,48,Сomplete higher education,Single,1,Yes,2,450000,Yes,2400,25,Yes,22000,1,150000,50.666667
10463,PR,51,Сomplete higher education,Divorced,2,Yes,2,600000,No,0,15,Yes,15000,1,70000,67.166667
10464,SP,48,Secondary education,Divorced,1,Yes,0,0,No,0,80,No,6100,2,48000,72.666667
10467,PR,51,Secondary education,Married,3,Yes,1,340000,Yes,4000,90,Yes,13000,2,180000,89.166667
10472,SP,48,Secondary education,Married,0,Yes,1,220000,No,0,18,Yes,2200,2,30000,23.000000

In [72]:
data1 = data.drop(data[data['recent_salary'] == 'no data'].index, axis=0)

In [73]:
data1['income_per_children'] = data1['recent_salary'] / (data1['number_of_children'] + 1)

In [74]:
data.groupby('property')['SCORE'].mean()

property
No     47.809748
Yes    54.972222
Name: SCORE, dtype: float64

In [75]:
data.groupby('education').agg({'age': 'mean', 'SCORE': 'mean', 'education': 'count'})

                                 age      SCORE  education
education
Secondary education        41.297143  49.950476       3150
Senior student             39.967980  50.215107       3654
Сomplete higher education  41.926471  52.848856       3672

In [76]:
data[(data['recent_salary'].isna()) | (data['recent_salary'] == 'no data')]

,department,age,education,social_status,number_of_children,property,number_of_properties,value_of_properties,outcome,outcome_amount,time_worked_since_last_employment_mnth,curr_working_status,recent_salary,number_of_cars,car_value,SCORE
4,RJ,28,Сomplete higher education,Divorced,2,No,1,370000,No,0,30,Yes,NaN,1,35000,34.166667
10459,RJ,45,Senior student,Single,1,Yes,1,185000,Yes,3000,19,Yes,no data,0,0,45.166667
10474,RJ,48,Сomplete higher education,Divorced,2,No,1,370000,No,0,30,Yes,NaN,1,35000,34.166667

In [77]:
data.duplicated().sum()

10088

In [78]:
data_wo_dups = data.drop_duplicates()

In [83]:
data.pivot_table(
    values='SCORE',
    index='department',
    columns='social_status',
    aggfunc='mean'
)

social_status   Divorced    Married     Single    Widowed
department
MG             56.096774  67.472222  37.477778  98.000000
PR             48.484848  54.958874  34.254902        NaN
RJ             41.116667  57.819444  35.850000  77.129630
SC             40.979167  54.496296  38.882353  71.944444
SP             49.814815  60.049242  34.101190  80.629630

In [ ]:
data['age_group'] = pd.cut(data['age'], bins=[0, 25, 35, 45, 100], labels=['0-25', '26-35', '36-45', '45+'], right=False)

In [93]:
data['recent_salary_num'] = pd.to_numeric(data['recent_salary'], errors='coerce')

In [95]:
data.groupby('age_group').agg({'recent_salary_num': 'mean', 'SCORE': 'mean'})

C:\Users\kosti\AppData\Local\Temp\ipykernel_8296\706854273.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  data.groupby('age_group').agg({'recent_salary_num': 'mean', 'SCORE': 'mean'})

           recent_salary_num      SCORE
age_group
0-25             7004.545455  40.154040
26-35            7280.380380  47.371470
36-45            9744.323484  49.168999
45+              8820.371851  56.342326

In [98]:
data.sort_values('car_value', ascending=False).head(5)

,department,age,education,social_status,number_of_children,property,number_of_properties,value_of_properties,outcome,outcome_amount,time_worked_since_last_employment_mnth,curr_working_status,recent_salary,number_of_cars,car_value,SCORE,age_group,recent_salary_num
5970,RJ,57,Secondary education,Married,3,Yes,1,340000,Yes,4000,90,Yes,13000,2,180000,89.166667,45+,13000.0
2158,PR,30,Secondary education,Married,3,Yes,1,340000,Yes,4000,90,Yes,13000,2,180000,89.166667,26-35,13000.0
971,RJ,42,Secondary education,Married,3,Yes,1,340000,Yes,4000,90,Yes,13000,2,180000,89.166667,36-45,13000.0
3276,PR,25,Secondary education,Married,3,Yes,1,340000,Yes,4000,90,Yes,13000,2,180000,89.166667,26-35,13000.0
7332,SC,23,Secondary education,Married,0,Yes,1,340000,Yes,4000,90,Yes,13000,2,180000,89.166667,0-25,13000.0

In [101]:
data[data['number_of_children'] > 0].shape[0] / data.shape[0]

0.6822260404734631

In [112]:
data.groupby('department')['outcome_amount'].mean().idxmax()

'MG'

In [ ]:
arr = np.arange(1, 21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [117]:
arr[1::2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [119]:
print(arr.mean())
print(arr.sum())
print(arr.min())
print(arr.max())

10.5
210
1
20

In [123]:
matrix = np.random.randn(4, 4)
matrix

array([[-0.14346334,  0.13010984, -0.39440446,  0.60936073],
       [-0.83909182,  0.74302064,  0.52345935,  1.88090734],
       [-1.04742147, -0.74590546, -0.79999354,  2.15053227],
       [ 1.13485064, -1.11281311, -1.53188479,  0.83188503]])

In [126]:
print(matrix.sum(axis=0))
print(matrix.sum(axis=1))

[-0.895126   -0.9855881  -2.20282344  5.47268537]
[ 0.20160276  2.30829551 -0.4427882  -0.67796224]

In [128]:
matrix[matrix < 0.5] = 0
matrix[matrix >= 0.5] = 1

In [130]:
a1 = np.random.randn(5, 5)
a2 = np.random.randn(5, 5)

a1 + a2

array([[ 1.33589774,  0.29471707,  0.83900021,  1.33717002,  2.00236343],
       [-0.20357401,  1.94866331,  0.67352818,  0.92313159,  1.09414356],
       [ 0.40423427, -0.96700469, -1.47127036, -0.46035274,  0.62074069],
       [-1.28910907, -0.68887218,  2.62751717, -1.30079563, -0.26625903],
       [-0.45595876,  0.37076726,  0.0718195 ,  4.1630712 , -0.59082696]])

In [131]:
a1 - a2

array([[-0.6498402 ,  1.21322401,  1.93885364,  0.04553634, -0.621235  ],
       [ 0.15250347, -1.72705612,  1.25349761,  0.17544317, -1.22467306],
       [ 1.86176735,  2.28862142,  1.56852655, -0.14140802, -0.865993  ],
       [ 0.46995844, -0.27111208, -0.18456722, -2.09727218, -1.17978058],
       [ 1.238215  , -1.71257359,  1.31599946,  0.7500945 ,  0.06292331]])

In [134]:
a1 * a2

array([[ 0.34058262, -0.34626358, -0.76380802,  0.44648752,  0.90588159],
       [ 0.00454627,  0.20364146, -0.27940401,  0.20534791, -0.0756685 ],
       [-0.82569308, -1.07567248, -0.07390976,  0.0479821 , -0.09115622],
       [ 0.36023532,  0.10026078,  1.71744536, -0.67662033, -0.33024709],
       [-0.3313195 , -0.69885998, -0.43167414,  4.19213002,  0.08627929]])

In [ ]:
np.where(matrix > matrix.mean())[0]

(array([0, 1, 1, 1, 2, 3, 3], dtype=int64),
 array([3, 1, 2, 3, 3, 0, 3], dtype=int64))

In [142]:
arr = np.arange(1, 13)
arr.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [147]:
arr = np.random.randn(1, 100)
arr[arr > 0.7].shape[0]

26